### ISSUE TITLE
[major][master] React tutorial

### ISSUE THREAD

**Issue by TcoiOleg** [TcoiOleg/DisciplineApp#21]
https://spring.io/guides/tutorials/react-and-spring-data-rest/

**Comment by TcoiOleg** [comment]
https://promisesaplus.com/
http://know.cujojs.com/tutorials/promises/consuming-promises

**Comment by TcoiOleg** [comment]
https://stackoverflow.com/questions/27182701/how-do-i-send-spring-csrf-token-from-postman-rest-client
https://habrahabr.ru/post/264641/

**Comment by TcoiOleg** [comment]
forgot add issue. PART 3: https://github.com/TcoiOleg/DisciplineApp/commit/29ce711e037127943c412d14f226a99588ebb186

**Comment by TcoiOleg** [comment]
app.js:195 Uncaught TypeError: Cannot read property 'self' of undefined
    at http://localhost:8888/built/bundle.js:281:71
    at Array.map (native)
    at HabitList.render (http://localhost:8888/built/bundle.js:280:45)
    at http://localhost:8888/built/bundle.js:16691:22
    at measureLifeCyclePerf (http://localhost:8888/built/bundle.js:15970:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:8888/built/bundle.js:16690:26)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:8888/built/bundle.js:16717:33)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:8888/built/bundle.js:16641:37)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:8888/built/bundle.js:16619:11)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:8888/built/bundle.js:16540:13)

**Comment by TcoiOleg** [comment]
All previous commits then in branch https://github.com/TcoiOleg/DisciplineApp/tree/development/react_tutorial

**Comment by TcoiOleg** [comment]
https://stackoverflow.com/questions/37603231/repositoryeventhandler-events-stop-with-repositoryrestcontroller
